# Generated by Django 4.1.2 on 2022-10-07 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkbook_app', '0002_remove_checkbook_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkbook',
            name='type',
            field=models.CharField(choices=[('Debit', 'Debit'), ('Credit', 'Credit')], max_length=6),
        ),
    ]
